### ISSUE TITLE
Name of play and play ID are not logged

### ISSUE THREAD

**Issue by pgporada** [ujenmr/ansible-logstash-callback#4]
Assuming the following playbook, one should expect a logged field for each play name in the playbook.

```
---
- name: Play 1
  hosts: localhost
  connection: local
  tasks:
    - name: Task 1
       shell: uptime

- name: Play 2
  hosts: localhost
  connection: local
  tasks:
    - name: Task 1
       shell: uname -a
...
```

What I would expect to see as a log entry would be 
```
{
        "ansible_type" => "start",
               "level" => "INFO",
             "session" => "87c7bf9e-f731-11e6-845a-2477032230c8",
             "message" => "START /tmp/kitchen/default.yml",
                "type" => "ansible",
    "ansible_playbook" => "/tmp/kitchen/default.yml",
    "ansible_play_name" => "Play 1",                               <============================
    "ansible_play_id" => "82cc5a17-d834-41a4-833b-79794311abff",   <============================
                "tags" => [],
                "path" => "/tmp/kitchen/callback_plugins/logstash.py",
          "@timestamp" => 2017-02-20T05:57:58.497Z,
                "port" => 43622,
            "@version" => "1",
                "host" => "laptappy",
         "logger_name" => "python-logstash-logger",
              "status" => "OK"
}
```

Thanks for creating this plugin in the first place! It's been really helpful so far. :smiley:  :+1:
